version: 2.1
orbs:
    node: circleci/node@4.1.0
    aws-cli: circleci/aws-cli@1.3.1
jobs:
    build-deploy:
        docker:
            - image: cimg/base:stable
        steps:
            - node/install
            - aws-cli/setup
            - checkout
            - run:
                name: install-ui
                command: |
                    npm run frontend:install
            - run:
                name: install-server
                command: |
                    npm run backend:install
            - run:
                name: build-ui
                command: |
                    npm run frontend:build
            - run:
                name: build-server
                command: |
                    npm run backend:build
            - run:
                name: test-server
                command: |
                    npm run backend:test
                environment:
                    ENV: test
            - run:
                name: deploy-ui
                command: |
                    npm run frontend:deploy
    deploy-backend:
        docker:
            - image: cimg/python:3.8
        working_directory: ~/project/Backend
        steps:
            - checkout
            - run:
                name: install ebcli
                command: |
                    cd Backend
                    pip install ebcli
            - run:
                name: deploy server
                command: |
                    cd Backend
                    eb deploy
workflows:
    version: 2
    build-and-deploy:
        jobs:
            - build-deploy
            - deploy-backend:
                requires:
                    - build-deploy